"""
AIuthor Backend — Book Assembler Service.

Compiles book text, metadata, and sections into a publication-ready manuscript.
"""
from __future__ import annotations

import logging
from uuid import UUID
from sqlalchemy.orm import Session
from sqlalchemy import asc

from app.models import BookProject, BookSection, Chapter
from app.models.memory import ConceptBible
from app.models.document import SourceDocument
from app.workflows.schemas import BookAssemblyRequest, AssembledChapter, BookAssemblyResponse
from app.services.book_service import BookProjectService
from app.services.continuity_pack_service import ContinuityPackService
from app.services.exceptions import NotFoundError
from app.schemas.section import REQUIRED_FRONT_MATTER_SECTIONS, REQUIRED_BACK_MATTER_SECTIONS

logger = logging.getLogger(__name__)


class BookAssemblerService:
    """
    Service to compile book elements into a publication-ready manuscript response structure.
    """

    def __init__(self, db: Session) -> None:
        self.db = db
        self.book_service = BookProjectService(db)
        self.continuity_pack_service = ContinuityPackService(db)

    def _get_book(self, book_id: UUID) -> BookProject:
        """Fetch BookProject, raising NotFoundError if missing."""
        return self.book_service.get_book_project(book_id)

    def _select_chapter_content(self, chapter: Chapter, prefer_final_text: bool = True) -> tuple[str, str, list[str]]:
        """
        Selects the best available chapter content according to priority,
        cleaning the manuscript and parsing JSON if necessary.
        
        Returns:
            tuple[content, source_field, warnings]
        """
        from app.utils.manuscript_content import extract_clean_chapter_manuscript

        return extract_clean_chapter_manuscript(
            final_text=chapter.final_text,
            edited_text=chapter.edited_text,
            humanized_text=chapter.humanized_text,
            draft_text=chapter.draft_text,
            summary=chapter.summary,
            chapter_number=chapter.chapter_number,
            chapter_title=chapter.title,
            prefer_final_text=prefer_final_text
        )

    def _load_front_matter(self, book: BookProject, include_toc: bool = True) -> list[dict]:
        """
        Loads front matter sections.
        
        If none exist in database, constructs virtual placeholders.
        """
        db_front = (
            self.db.query(BookSection)
            .filter(
                BookSection.book_id == book.id,
                (BookSection.section_type.in_(REQUIRED_FRONT_MATTER_SECTIONS) | (BookSection.sort_order < 1000))
            )
            .order_by(asc(BookSection.sort_order), asc(BookSection.created_at))
            .all()
        )

        front_matter = []
        if db_front:
            for s in db_front:
                front_matter.append({
                    "section_type": s.section_type,
                    "title": s.title or s.section_type.replace("_", " ").title(),
                    "content": s.content or ""
                })
        else:
            # Virtual front matter
            front_matter.append({
                "section_type": "title_page",
                "title": "Title Page",
                "content": f"{book.topic}\n\nGenerated by AIuthor"
            })
            front_matter.append({
                "section_type": "copyright",
                "title": "Copyright",
                "content": "Copyright © 2026. All rights reserved."
            })
            if include_toc:
                front_matter.append({
                    "section_type": "toc",
                    "title": "Table of Contents",
                    "content": "Table of Contents Placeholder"
                })

        return front_matter

    def _load_back_matter(self, book: BookProject, include_glossary: bool = True, include_bibliography: bool = True) -> list[dict]:
        """
        Loads back matter sections.
        
        If none exist in database, constructs virtual placeholders.
        """
        db_back = (
            self.db.query(BookSection)
            .filter(
                BookSection.book_id == book.id,
                (BookSection.section_type.in_(REQUIRED_BACK_MATTER_SECTIONS) | (BookSection.sort_order >= 1000))
            )
            .order_by(asc(BookSection.sort_order), asc(BookSection.created_at))
            .all()
        )

        back_matter = []
        if db_back:
            for s in db_back:
                back_matter.append({
                    "section_type": s.section_type,
                    "title": s.title or s.section_type.replace("_", " ").title(),
                    "content": s.content or ""
                })
        else:
            # Virtual back matter
            back_matter.append({
                "section_type": "conclusion",
                "title": "Conclusion",
                "content": "Conclusion placeholder for this book."
            })
            if include_glossary:
                glossary_items = self._build_glossary(book.id)
                content_lines = ["Glossary:\n"]
                for item in glossary_items:
                    content_lines.append(f"{item['concept']}: {item['definition']}")
                back_matter.append({
                    "section_type": "glossary",
                    "title": "Glossary",
                    "content": "\n".join(content_lines) if glossary_items else "No glossary entries available."
                })
            if include_bibliography:
                bib_items = self._build_bibliography(book.id)
                content_lines = ["Bibliography:\n"]
                for item in bib_items:
                    citation = item.get("citation") or f"{item['title']} ({item['source_type']})"
                    if item.get("source_url"):
                        citation += f" - {item['source_url']}"
                    content_lines.append(f"- {citation}")
                back_matter.append({
                    "section_type": "bibliography",
                    "title": "Bibliography",
                    "content": "\n".join(content_lines) if bib_items else "No bibliography entries available."
                })

        return back_matter

    def _build_toc(self, chapters: list[AssembledChapter]) -> list[dict]:
        """Builds a Table of Contents list of dicts."""
        return [
            {
                "chapter_number": ch.chapter_number,
                "title": ch.title,
                "chapter_id": str(ch.chapter_id)
            }
            for ch in chapters
        ]

    def _build_glossary(self, book_id: UUID) -> list[dict]:
        """Fetches concepts from ConceptBible table."""
        concepts = (
            self.db.query(ConceptBible)
            .filter(ConceptBible.book_id == book_id)
            .order_by(asc(ConceptBible.concept))
            .all()
        )
        return [
            {
                "concept": c.concept,
                "definition": c.definition or ""
            }
            for c in concepts
        ]

    def _build_bibliography(self, book_id: UUID) -> list[dict]:
        """Fetches bibliography entries from SourceDocument table."""
        docs = (
            self.db.query(SourceDocument)
            .filter(SourceDocument.book_id == book_id)
            .order_by(asc(SourceDocument.title))
            .all()
        )
        return [
            {
                "title": d.title,
                "source_type": d.source_type,
                "source_url": d.source_url,
                "citation": (d.document_metadata or {}).get("citation")
            }
            for d in docs
        ]

    def assemble_book(self, request: BookAssemblyRequest) -> BookAssemblyResponse:
        """
        Assembles all elements of the book into a response object.
        
        This method is offline and does not call any LLM/API.
        """
        book = self._get_book(request.book_id)

        # Load chapters ordered by chapter_number
        chapters = (
            self.db.query(Chapter)
            .filter(Chapter.book_id == book.id)
            .order_by(asc(Chapter.chapter_number))
            .all()
        )

        assembled_chapters = []
        for ch in chapters:
            content, source_field, warnings = self._select_chapter_content(ch, prefer_final_text=request.prefer_final_text)
            if not content or not content.strip():
                continue
            
            from app.utils.manuscript_content import try_parse_json_text
            source_val = getattr(ch, source_field, None) if source_field != "placeholder" else None
            is_json_extracted = False
            if source_val:
                is_json_extracted = try_parse_json_text(source_val) is not None

            ch_metadata = dict(ch.chapter_contract) if ch.chapter_contract else {}
            ch_metadata.update({
                "content_source_field": source_field,
                "manuscript_cleaning_enabled": True,
                "extraction_warnings": warnings,
                "rejected_debug_dump": any("rejected: looks like a debug or prompt dump" in w for w in warnings),
                "json_content_extracted": is_json_extracted
            })

            assembled_chapters.append(AssembledChapter(
                chapter_id=ch.id,
                chapter_number=ch.chapter_number,
                title=ch.title,
                content=content,
                source_field=source_field,
                word_count=len(content.split()),
                metadata=ch_metadata
            ))

        # Extract title details from project metadata
        metadata = book.project_metadata or {}
        title = metadata.get("title") or book.topic
        subtitle = metadata.get("subtitle")
        author = metadata.get("author") or "AIuthor System"

        front_matter = self._load_front_matter(book, include_toc=request.include_toc) if request.include_front_matter else []
        back_matter = self._load_back_matter(
            book,
            include_glossary=request.include_glossary,
            include_bibliography=request.include_bibliography
        ) if request.include_back_matter else []
        
        toc = self._build_toc(assembled_chapters) if request.include_toc else []
        glossary = self._build_glossary(book.id) if request.include_glossary else []
        bibliography = self._build_bibliography(book.id) if request.include_bibliography else []

        total_chapters = len(assembled_chapters)
        total_words = sum(c.word_count for c in assembled_chapters)

        return BookAssemblyResponse(
            book_id=book.id,
            run_id=request.run_id,
            title=title,
            subtitle=subtitle,
            author=author,
            front_matter=front_matter,
            chapters=assembled_chapters,
            back_matter=back_matter,
            toc=toc,
            glossary=glossary,
            bibliography=bibliography,
            total_chapters=total_chapters,
            total_words=total_words,
            metadata=metadata
        )
