"""create observability tables

Revision ID: 4e2f63ead048
Revises: b6c0460dc12f
Create Date: 2026-05-22 23:36:52.109957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '4e2f63ead048'
down_revision: Union[str, None] = 'b6c0460dc12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('run_id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['book_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_agent_name'), 'agent_traces', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_traces_book_id'), 'agent_traces', ['book_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_run_id'), 'agent_traces', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_status'), 'agent_traces', ['status'], unique=False)
    op.create_table('memory_io_logs',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('run_id', app.models.base.GUID(), nullable=True),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('memory_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['book_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_io_logs_agent_name'), 'memory_io_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_memory_io_logs_book_id'), 'memory_io_logs', ['book_id'], unique=False)
    op.create_index(op.f('ix_memory_io_logs_memory_type'), 'memory_io_logs', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_io_logs_operation'), 'memory_io_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_memory_io_logs_run_id'), 'memory_io_logs', ['run_id'], unique=False)
    op.create_table('prompt_logs',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('run_id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['book_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_logs_agent_name'), 'prompt_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_prompt_logs_book_id'), 'prompt_logs', ['book_id'], unique=False)
    op.create_index(op.f('ix_prompt_logs_model_name'), 'prompt_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_prompt_logs_prompt_name'), 'prompt_logs', ['prompt_name'], unique=False)
    op.create_index(op.f('ix_prompt_logs_run_id'), 'prompt_logs', ['run_id'], unique=False)
    op.create_table('token_cost_ledger',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('run_id', app.models.base.GUID(), nullable=True),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('ledger_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['book_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_cost_ledger_agent_name'), 'token_cost_ledger', ['agent_name'], unique=False)
    op.create_index(op.f('ix_token_cost_ledger_book_id'), 'token_cost_ledger', ['book_id'], unique=False)
    op.create_index(op.f('ix_token_cost_ledger_model_name'), 'token_cost_ledger', ['model_name'], unique=False)
    op.create_index(op.f('ix_token_cost_ledger_run_id'), 'token_cost_ledger', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_cost_ledger_run_id'), table_name='token_cost_ledger')
    op.drop_index(op.f('ix_token_cost_ledger_model_name'), table_name='token_cost_ledger')
    op.drop_index(op.f('ix_token_cost_ledger_book_id'), table_name='token_cost_ledger')
    op.drop_index(op.f('ix_token_cost_ledger_agent_name'), table_name='token_cost_ledger')
    op.drop_table('token_cost_ledger')
    op.drop_index(op.f('ix_prompt_logs_run_id'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_prompt_name'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_model_name'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_book_id'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_agent_name'), table_name='prompt_logs')
    op.drop_table('prompt_logs')
    op.drop_index(op.f('ix_memory_io_logs_run_id'), table_name='memory_io_logs')
    op.drop_index(op.f('ix_memory_io_logs_operation'), table_name='memory_io_logs')
    op.drop_index(op.f('ix_memory_io_logs_memory_type'), table_name='memory_io_logs')
    op.drop_index(op.f('ix_memory_io_logs_book_id'), table_name='memory_io_logs')
    op.drop_index(op.f('ix_memory_io_logs_agent_name'), table_name='memory_io_logs')
    op.drop_table('memory_io_logs')
    op.drop_index(op.f('ix_agent_traces_status'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_run_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_book_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_agent_name'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
