"""create core book tables

Revision ID: 8fc8c1e49027
Revises: 77e49bd64f10
Create Date: 2026-05-22 23:20:34.384705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '8fc8c1e49027'
down_revision: Union[str, None] = '77e49bd64f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_projects',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('reader_profile', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('target_chapters', sa.Integer(), nullable=False),
    sa.Column('words_per_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('project_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_projects_created_at', 'book_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_projects_genre'), 'book_projects', ['genre'], unique=False)
    op.create_index(op.f('ix_book_projects_status'), 'book_projects', ['status'], unique=False)
    op.create_index(op.f('ix_book_projects_tone'), 'book_projects', ['tone'], unique=False)
    op.create_table('book_runs',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_agent', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_runs_book_id'), 'book_runs', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_runs_current_agent'), 'book_runs', ['current_agent'], unique=False)
    op.create_index(op.f('ix_book_runs_status'), 'book_runs', ['status'], unique=False)
    op.create_table('book_sections',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('section_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_sections_book_id'), 'book_sections', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_sections_section_type'), 'book_sections', ['section_type'], unique=False)
    op.create_index(op.f('ix_book_sections_sort_order'), 'book_sections', ['sort_order'], unique=False)
    op.create_index(op.f('ix_book_sections_status'), 'book_sections', ['status'], unique=False)
    op.create_table('chapters',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('chapter_contract', sa.JSON(), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('humanized_text', sa.Text(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'chapter_number', name='uq_chapters_book_id_chapter_number')
    )
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.create_index(op.f('ix_chapters_tone'), 'chapters', ['tone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_tone'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_book_sections_status'), table_name='book_sections')
    op.drop_index(op.f('ix_book_sections_sort_order'), table_name='book_sections')
    op.drop_index(op.f('ix_book_sections_section_type'), table_name='book_sections')
    op.drop_index(op.f('ix_book_sections_book_id'), table_name='book_sections')
    op.drop_table('book_sections')
    op.drop_index(op.f('ix_book_runs_status'), table_name='book_runs')
    op.drop_index(op.f('ix_book_runs_current_agent'), table_name='book_runs')
    op.drop_index(op.f('ix_book_runs_book_id'), table_name='book_runs')
    op.drop_table('book_runs')
    op.drop_index(op.f('ix_book_projects_tone'), table_name='book_projects')
    op.drop_index(op.f('ix_book_projects_status'), table_name='book_projects')
    op.drop_index(op.f('ix_book_projects_genre'), table_name='book_projects')
    op.drop_index('idx_book_projects_created_at', table_name='book_projects')
    op.drop_table('book_projects')
    # ### end Alembic commands ###
