"""create memory tables

Revision ID: b6c0460dc12f
Revises: f1826ee9cd8a
Create Date: 2026-05-22 23:32:11.996667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'b6c0460dc12f'
down_revision: Union[str, None] = 'f1826ee9cd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callback_index',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('source_chapter', sa.Integer(), nullable=True),
    sa.Column('target_chapter', sa.Integer(), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('callback_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('callback_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callback_index_book_id'), 'callback_index', ['book_id'], unique=False)
    op.create_index(op.f('ix_callback_index_concept'), 'callback_index', ['concept'], unique=False)
    op.create_index(op.f('ix_callback_index_source_chapter'), 'callback_index', ['source_chapter'], unique=False)
    op.create_index(op.f('ix_callback_index_status'), 'callback_index', ['status'], unique=False)
    op.create_index(op.f('ix_callback_index_target_chapter'), 'callback_index', ['target_chapter'], unique=False)
    op.create_table('character_bible',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('character_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('arc_summary', sa.Text(), nullable=True),
    sa.Column('appears_in_chapters', sa.JSON(), nullable=True),
    sa.Column('character_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'character_name', name='uq_character_bible_book_id_character_name')
    )
    op.create_index(op.f('ix_character_bible_book_id'), 'character_bible', ['book_id'], unique=False)
    op.create_index(op.f('ix_character_bible_character_name'), 'character_bible', ['character_name'], unique=False)
    op.create_table('concept_bible',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('first_chapter', sa.Integer(), nullable=True),
    sa.Column('related_terms', sa.JSON(), nullable=True),
    sa.Column('appears_in_chapters', sa.JSON(), nullable=True),
    sa.Column('concept_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'concept', name='uq_concept_bible_book_id_concept')
    )
    op.create_index(op.f('ix_concept_bible_book_id'), 'concept_bible', ['book_id'], unique=False)
    op.create_index(op.f('ix_concept_bible_concept'), 'concept_bible', ['concept'], unique=False)
    op.create_index(op.f('ix_concept_bible_first_chapter'), 'concept_bible', ['first_chapter'], unique=False)
    op.create_table('decision_log',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('decision_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_log_created_at', 'decision_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_log_book_id'), 'decision_log', ['book_id'], unique=False)
    op.create_table('tone_fingerprints',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('tone_name', sa.String(length=50), nullable=False),
    sa.Column('sentence_rhythm', sa.JSON(), nullable=True),
    sa.Column('lexical_rules', sa.JSON(), nullable=True),
    sa.Column('banned_phrases', sa.JSON(), nullable=True),
    sa.Column('example_phrases', sa.JSON(), nullable=True),
    sa.Column('fingerprint_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tone_fingerprints_book_id'), 'tone_fingerprints', ['book_id'], unique=False)
    op.create_index(op.f('ix_tone_fingerprints_tone_name'), 'tone_fingerprints', ['tone_name'], unique=False)
    op.create_table('fact_registry',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=False),
    sa.Column('chapter_id', app.models.base.GUID(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source_document_id', app.models.base.GUID(), nullable=True),
    sa.Column('source_chunk_id', app.models.base.GUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('used_in_chapters', sa.JSON(), nullable=True),
    sa.Column('fact_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_registry_book_id'), 'fact_registry', ['book_id'], unique=False)
    op.create_index(op.f('ix_fact_registry_chapter_id'), 'fact_registry', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_fact_registry_confidence'), 'fact_registry', ['confidence'], unique=False)
    op.create_index(op.f('ix_fact_registry_source_chunk_id'), 'fact_registry', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_fact_registry_source_document_id'), 'fact_registry', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_fact_registry_status'), 'fact_registry', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_registry_status'), table_name='fact_registry')
    op.drop_index(op.f('ix_fact_registry_source_document_id'), table_name='fact_registry')
    op.drop_index(op.f('ix_fact_registry_source_chunk_id'), table_name='fact_registry')
    op.drop_index(op.f('ix_fact_registry_confidence'), table_name='fact_registry')
    op.drop_index(op.f('ix_fact_registry_chapter_id'), table_name='fact_registry')
    op.drop_index(op.f('ix_fact_registry_book_id'), table_name='fact_registry')
    op.drop_table('fact_registry')
    op.drop_index(op.f('ix_tone_fingerprints_tone_name'), table_name='tone_fingerprints')
    op.drop_index(op.f('ix_tone_fingerprints_book_id'), table_name='tone_fingerprints')
    op.drop_table('tone_fingerprints')
    op.drop_index(op.f('ix_decision_log_book_id'), table_name='decision_log')
    op.drop_index('idx_decision_log_created_at', table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index(op.f('ix_concept_bible_first_chapter'), table_name='concept_bible')
    op.drop_index(op.f('ix_concept_bible_concept'), table_name='concept_bible')
    op.drop_index(op.f('ix_concept_bible_book_id'), table_name='concept_bible')
    op.drop_table('concept_bible')
    op.drop_index(op.f('ix_character_bible_character_name'), table_name='character_bible')
    op.drop_index(op.f('ix_character_bible_book_id'), table_name='character_bible')
    op.drop_table('character_bible')
    op.drop_index(op.f('ix_callback_index_target_chapter'), table_name='callback_index')
    op.drop_index(op.f('ix_callback_index_status'), table_name='callback_index')
    op.drop_index(op.f('ix_callback_index_source_chapter'), table_name='callback_index')
    op.drop_index(op.f('ix_callback_index_concept'), table_name='callback_index')
    op.drop_index(op.f('ix_callback_index_book_id'), table_name='callback_index')
    op.drop_table('callback_index')
    # ### end Alembic commands ###
