"""create rag source tables

Revision ID: f1826ee9cd8a
Revises: 8fc8c1e49027
Create Date: 2026-05-22 23:28:16.609848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'f1826ee9cd8a'
down_revision: Union[str, None] = '8fc8c1e49027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_documents_created_at', 'source_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_documents_book_id'), 'source_documents', ['book_id'], unique=False)
    op.create_index(op.f('ix_source_documents_source_type'), 'source_documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_source_documents_status'), 'source_documents', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('document_id', app.models.base.GUID(), nullable=False),
    sa.Column('book_id', app.models.base.GUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_id_chunk_index')
    )
    op.create_index('idx_document_chunks_created_at', 'document_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_book_id'), 'document_chunks', ['book_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_embedding_status'), 'document_chunks', ['embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_status'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_book_id'), table_name='document_chunks')
    op.drop_index('idx_document_chunks_created_at', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_source_documents_status'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_source_type'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_book_id'), table_name='source_documents')
    op.drop_index('idx_source_documents_created_at', table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
