from __future__ import annotations

from datetime import datetime
from uuid import UUID
from typing import Any
from pydantic import Field, field_validator
from app.schemas.base import BaseSchema, ORMBaseSchema
from app.schemas.enums import ChapterStatus, TonePreset


class ChapterContract(BaseSchema):
    """
    Structured planning contract generated by Planner Agent for each chapter.
    """
    chapter_number: int = Field(..., ge=1, le=100)
    title: str = Field(..., min_length=2, max_length=300)
    purpose: str = Field(..., min_length=5, max_length=1000)
    key_concepts: list[str] = Field(default_factory=list)
    required_facts: list[str] = Field(default_factory=list)
    callback_opportunities: list[str] = Field(default_factory=list)
    estimated_word_count: int | None = Field(None, ge=100, le=20000)
    metadata: dict | None = None

    @field_validator("title", "purpose", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class ChapterCreate(BaseSchema):
    """
    Schema for creating chapter records from planner agent output.
    """
    book_id: UUID
    chapter_number: int = Field(..., ge=1, le=100)
    title: str = Field(..., min_length=2, max_length=300)
    summary: str | None = Field(None, max_length=5000)
    chapter_contract: dict | ChapterContract | None = None
    tone: TonePreset | None = None
    status: ChapterStatus = ChapterStatus.PLANNED

    @field_validator("title", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class ChapterUpdate(BaseSchema):
    """
    Schema used by agents and update APIs to modify chapter content or status.
    """
    title: str | None = Field(None, min_length=2, max_length=300)
    summary: str | None = Field(None, max_length=5000)
    chapter_contract: dict | ChapterContract | None = None
    draft_text: str | None = None
    humanized_text: str | None = None
    edited_text: str | None = None
    final_text: str | None = None
    tone: TonePreset | None = None
    status: ChapterStatus | None = None
    word_count: int | None = Field(None, ge=0)

    @field_validator("title", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class ChapterResponse(ORMBaseSchema):
    """
    Response schema returning complete details for a single chapter.
    """
    book_id: UUID
    chapter_number: int
    title: str
    summary: str | None
    chapter_contract: dict | None
    draft_text: str | None
    humanized_text: str | None
    edited_text: str | None
    final_text: str | None
    tone: str | None
    status: str
    word_count: int | None


class ChapterListItem(BaseSchema):
    """
    Lightweight chapter representation for preview and navigation dashboards.
    """
    id: UUID
    book_id: UUID
    chapter_number: int
    title: str
    summary: str | None
    tone: str | None
    status: str
    word_count: int | None
    updated_at: datetime | None


class ChapterInsertRequest(BaseSchema):
    """
    Input schema for inserting a chapter in insert/repair flows.
    """
    after_chapter: int = Field(..., ge=0, le=100)
    title: str = Field(..., min_length=2, max_length=300)
    purpose: str = Field(..., min_length=5, max_length=1000)
    tone: TonePreset | None = None
    metadata: dict | None = None

    @field_validator("title", "purpose", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v
