from __future__ import annotations

from datetime import datetime
from uuid import UUID
from typing import Any, Literal
from pydantic import Field, field_validator, model_validator
from app.schemas.base import BaseSchema, ORMBaseSchema


class SourceDocumentCreate(BaseSchema):
    """
    Schema for saving uploaded, manual, or web source documents.
    """
    book_id: UUID | None = None
    title: str = Field(..., min_length=2, max_length=500)
    source_type: str = Field(..., min_length=2, max_length=100)
    source_url: str | None = Field(None, max_length=2000)
    raw_text: str | None = None
    document_metadata: dict | None = None
    status: str = Field("created", max_length=50)

    @field_validator("title", "source_type", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class SourceDocumentUpdate(BaseSchema):
    """
    Schema for updating source document metadata or status.
    """
    title: str | None = Field(None, min_length=2, max_length=500)
    source_type: str | None = Field(None, min_length=2, max_length=100)
    source_url: str | None = Field(None, max_length=2000)
    raw_text: str | None = None
    document_metadata: dict | None = None
    status: str | None = Field(None, max_length=50)

    @field_validator("title", "source_type", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class SourceDocumentResponse(ORMBaseSchema):
    """
    Response schema returning complete details of a source document.
    """
    book_id: UUID | None
    title: str
    source_type: str
    source_url: str | None
    raw_text: str | None
    document_metadata: dict | None
    status: str


class SourceDocumentListItem(BaseSchema):
    """
    Lightweight summary schema for listing source documents.
    """
    id: UUID
    book_id: UUID | None
    title: str
    source_type: str
    source_url: str | None
    status: str
    created_at: datetime | None
    updated_at: datetime | None


class DocumentChunkCreate(BaseSchema):
    """
    Schema used when saving text chunks generated by a chunking service.
    """
    document_id: UUID
    book_id: UUID | None = None
    chunk_index: int = Field(..., ge=0)
    chunk_text: str = Field(..., min_length=1)
    token_count: int | None = Field(None, ge=0)
    chunk_metadata: dict | None = None
    embedding_model: str | None = Field(None, max_length=100)
    embedding_status: str = Field("pending", max_length=50)

    @field_validator("chunk_text", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class DocumentChunkUpdate(BaseSchema):
    """
    Schema for updating document chunks during embedding calculations or metadata updates.
    """
    chunk_text: str | None = Field(None, min_length=1)
    token_count: int | None = Field(None, ge=0)
    chunk_metadata: dict | None = None
    embedding_model: str | None = Field(None, max_length=100)
    embedding_status: str | None = Field(None, max_length=50)

    @field_validator("chunk_text", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class DocumentChunkResponse(ORMBaseSchema):
    """
    Response schema returning complete details for a document chunk.
    """
    document_id: UUID
    book_id: UUID | None
    chunk_index: int
    chunk_text: str
    token_count: int | None
    chunk_metadata: dict | None
    embedding_model: str | None
    embedding_status: str


class DocumentChunkListItem(BaseSchema):
    """
    Lightweight chunk representation for listing schemas.
    """
    id: UUID
    document_id: UUID
    book_id: UUID | None
    chunk_index: int
    token_count: int | None
    embedding_status: str
    created_at: datetime | None


class ChunkingRequest(BaseSchema):
    """
    Request schema to trigger text chunking.
    """
    document_id: UUID
    chunk_size: int = Field(1000, ge=200, le=5000)
    chunk_overlap: int = Field(150, ge=0, le=1000)
    strategy: Literal["recursive", "paragraph", "sentence", "fixed"] = "recursive"

    @model_validator(mode="after")
    def validate_overlap(self) -> ChunkingRequest:
        if self.chunk_overlap >= self.chunk_size:
            raise ValueError("chunk_overlap must be less than chunk_size")
        return self


class ChunkingResponse(BaseSchema):
    """
    Response detailing text chunking execution results.
    """
    document_id: UUID
    chunks_created: int = Field(..., ge=0)
    strategy: str
    chunk_size: int
    chunk_overlap: int
    status: str
    message: str | None = None


class RetrievalRequest(BaseSchema):
    """
    Input schema to query the RAG retriever.
    """
    book_id: UUID | None = None
    query: str = Field(..., min_length=2, max_length=1000)
    top_k: int = Field(8, ge=1, le=20)
    include_raw_text: bool = True
    filters: dict | None = None

    @field_validator("query", mode="before")
    @classmethod
    def strip_whitespace(cls, v: Any) -> Any:
        if isinstance(v, str):
            return v.strip()
        return v


class RetrievalResultItem(BaseSchema):
    """
    Represents a single retrieved text chunk candidate.
    """
    chunk_id: UUID
    document_id: UUID
    book_id: UUID | None
    chunk_text: str | None = None
    score: float | None = Field(None, ge=0.0)
    source_title: str | None = None
    source_url: str | None = None
    metadata: dict | None = None


class RetrievalResponse(BaseSchema):
    """
    Response schema returning list of retrieval matches.
    """
    query: str
    top_k: int = Field(..., ge=1)
    results: list[RetrievalResultItem]
    total_results: int = Field(..., ge=0)
    status: str
    message: str | None = None
